name: AdaBibleChurch
favicon: null
layout_spectrum: 0.15688223741017282
typography_spectrum: 0.6762162649538368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.40159060969017446
  lightness: 0.2746987205464393
  saturation: 0.4989774548448622
  rhythmicContrast: 0.6165706657338887
purpose: []
